services:
  mysql:
    image: mysql:8.4
    container_name: attendease-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: attendance_db
      MYSQL_USER: attendance_user
      MYSQL_PASSWORD: attendance_pass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
  mongo:
    image: mongo:7
    container_name: attendease-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
volumes:
  mysql_data:
  mongo_data:
